services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nlpdb_system
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "6004:9000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root123@db/nlpdb_system
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: